services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
  mysql:
    image: mysql
    container_name: mysql_todos
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
      MYSQL_USER: todos
      MYSQL_PASSWORD: secret